name: CI/CD for ML Pipline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]


jobs:
    build-test-train:
        runs-on: ubuntu-latest

        steps:
            # step 1: check out repository
            - name: Checkout code
              uses: actions/checkout@v4

            # step 2: set up python
            - name: Setup Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"

            # step 3: Install dependancy
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirments.txt 

            # step 4: 
            - name: Run unit tests
              run: pytest -v

            # step 5: train the ml model
            - name: Train model
              run: python src/train.py

            # step 6: Evaluate model
            - name: Evaluate model
              run: python src/evaluate.py

            # step 7: Upload trained model
            - name: Upload model artifact
              uses: actions/upload-artifact@v4
              with:
                name: trained-model
                path: models/model.pkl

    deploy:
        needs: build-test-train
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'


        steps:
            - name: Checkout repositry
              uses: actions/checkout@v4

            - name: Download trained model
              uses: actions/download-artifact@v4

              with:
                name: trained-model
                path: models/


            - name: Deploy model(simulation)
              run: |
                echo "Deployment simulation successful"
                echo "Train model ready at models/model.pkl"